data:
  train_csv: "./datasets/data_TCRpHLA/random/train_data.csv"
  val_csv: "./datasets/data_TCRpHLA/random/val_data.csv"
  independent_test_csv: "./datasets/data_TCRpHLA/random/test_data.csv"
  external_test_csv: "./datasets/data_TCRpHLA/random/dbpepneo_data.csv"

  embedding_dict_path: "../PAGA/models/ESMc/ESMcEmbedding/embeddingDict.pkl"
  embedding_root: "../PAGA/models/ESMc/ESMcEmbedding"
  max_length: 34

training:
  batch_size: 256
  epochs: 200
  log_interval: 100
  learning_rate: 0.00001
  weight_decay: 0.0
  device: "cuda:0"
  num_workers: 5

testing:
  model_path: "./final_model_states/PAGA_random.pt"

output_path: "./outputs/"